# 
# LAST UPDATE: 2021-06-04 15:25:00-5
#=================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: localhost #change to your hostname if running your own instance
        port: 5050
    url: ${URL} #change to host URL  if running your own instance
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    languages: en-US
    cors: true
    pretty_print: true
    limit: 100
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '<a href="https://www.openstreetmap.org/copyright">Â© OpenStreetMap contributors</a>'
    # manager:
    #    name: TinyDB
    #    connection: /tmp/pygeoapi-process-manager.db
    #    output_dir: /tmp/
    ogc_schemas_location: /opt/schemas.opengis.net
#    templates:
#      path: /skin-dashboard/templates
#      static: /skin-dashboard/static

logging:
    level: ERROR
    # logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: 
            en: MERIT-based vector features
        description: 
            en: Provides flowpath/ mainstem features based on MERIT
        keywords:
            en:
                - geospatial
                - data
                - api
                - rivers
                - mainstems
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://github.com/ksonda/global-river-runner
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Kyle Onda
        url: https://github.com/ksonda
    contact:
        address: 2111 Campus Dr
        city: Durham
        stateorprovince: North Carolina
        postalcode: 27708
        country: USA
        email: kyle.onda@duke.edu
        url: https://internetofwater.org
        role: pointOfContact

resources:
    merit:
        type: collection
        title: 
            en: merit
        description: 
            en: merit features
        keywords:
            en:
                - rivers
        context:
            - schema: https://schema.org/
              nameid: schema:name
        links:
            - type: application/html
              rel: canonical
              title: source
              href: https://www.sciencebase.gov/catalog/item/614a8864d34e0df5fb97572d
              hreflang: en-US
            - type: application/html
              rel: cannonical
              title: github
              href: https://github.com/ksonda/global-river-runner
              hreflang: en-US
            - type: application/html
              rel: cannonical
              title: application
              href: https://river-runner-global.vercel.app/
              hreflang: en-US
            - type: application/html
              rel: canonical
              title: information
              href: https://www.usgs.gov/core-science-systems/ngp/national-hydrography/value-added-attributes-vaas
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: null
                end: null
        providers:
            - type: feature
              name: PostgreSQL
              data:
                host: ${POSTGRES_HOST}
                dbname: ${POSTGRES_DB}
                user: ${POSTGRES_USER}
                password: ${POSTGRES_PASSWORD}
                search_path: [public]
              geom_field: wkb_geometry
              id_field: ogc_fid
              table: merit_plus

    river-runner:
        type: process
        processor:
            name: RiverRunner
        title:
            en: River Runner
        description:
            en: A process that takes a set of coordinates in the world, and returns the largest flowpath to its terminal flowpoint.
        keywords:
            en:
                - rivers
                - river-runner
        links:
            - type: application/html
              rel: canonical
              title: source
              href: https://www.sciencebase.gov/catalog/item/614a8864d34e0df5fb97572d
              hreflang: en-US
            - type: application/html
              rel: cannonical
              title: github
              href: https://github.com/ksonda/global-river-runner
              hreflang: en-US
            - type: application/html
              rel: cannonical
              title: application
              href: https://river-runner.samlearner.com/
              hreflang: en-US
