# 
# LAST UPDATE: 2021-06-04 15:25:00-5
#=================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: localhost #change to your hostname if running your own instance
        port: 5050
    url: https://merit-nldi.internetofwater.app #change to host URL  if running your own instance
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    languages: en-US
    cors: true
    pretty_print: true
    limit: 100
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '<a href="https://www.openstreetmap.org/copyright">Â© OpenStreetMap contributors</a>'
    # manager:
    #    name: TinyDB
    #    connection: /tmp/pygeoapi-process-manager.db
    #    output_dir: /tmp/
    ogc_schemas_location: /opt/schemas.opengis.net
#    templates:
#      path: /skin-dashboard/templates
#      static: /skin-dashboard/static

logging:
    level: ERROR
    logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: 
            en: MERIT-based vector features
        description: 
            en: Provides flowpath/ mainstem features based on MERIT
        keywords:
            en:
                - geospatial
                - data
                - api
                - rivers
                - mainstems
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://github.com/ksonda/global-river-runner
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Kyle Onda
        url: https://github.com/ksonda
    contact:
        address: 2111 Campus Dr
        city: Durham
        stateorprovince: North Carolina
        postalcode: 27708
        country: USA
        email: kyle.onda@duke.edu
        url: https://internetofwater.org
        role: pointOfContact
resources:
    merit:
        type: collection
        title: 
            en: merit
        description: 
            en: merit features
        keywords:
            en:
                - rivers
        context:
            - schema: https://schema.org/
              nameid: schema:name
        links:
            - type: application/html
              rel: canonical
              title: source
              href: https://www.sciencebase.gov/catalog/item/614a8864d34e0df5fb97572d
              hreflang: en-US
            - type: application/html
              rel: canonical
              title: download
              href: https://prod-is-usgs-sb-prod-publish.s3.amazonaws.com/614a8864d34e0df5fb97572d/merit_plus_simplify.zip
              hreflang: en-US
            - type: application/html
              rel: canonical
              title: information
              href: https://www.usgs.gov/core-science-systems/ngp/national-hydrography/value-added-attributes-vaas
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: null
                end: null
        providers:
    #         - type: feature
    #           name: SQLiteGPKG
    #           data: /data/merit_plus_simplify.gpkg
    #           id_field: comid
    #           table: merit_plus
            - type: feature
              name: PostgreSQL
              data:
                host: /cloudsql/global-river-runner:us-central1:global-river-runner-db
                dbname: merit
                user: postgres
                password: geoconnex
                search_path: [public]
              geom_field: wkb_geometry
              id_field: comid
              table: merit_plus

    river-runner:
        type: process
        version: 0.1.0
        id: river-runner
        title:
            en: River Runner
        description:
            en: A process that takes a set of coordinates in the world, and returns the largest flowpath from it to its terminal flowpoint.
        keywords:
            en:
                - rivers
                - river-runner
        links:
            - type: application/html
              rel: canonical
              title: source
              href: https://www.sciencebase.gov/catalog/item/614a8864d34e0df5fb97572d
              hreflang: en-US
            - type: application/html
              rel: cannonical
              title: github
              href: https://github.com/ksonda/global-river-runner
              hreflang: en-US
            - type: application/html
              rel: cannonical
              title: application
              href: https://river-runner.samlearner.com/
              hreflang: en-US
        processor:
            name: RiverRunner
        inputs:
            bbox:
                title:
                    en: Bounding Box
                description:
                    en: Boundary box to begin a river runner query from
                keywords:
                    en: [box, coordinates]
                schema:
                    type: object
                    default: []
                minOccurs: 0
                maxOccurs: 1
                metadata: null
            lat:
                title: 
                    en: Latitude
                description: 
                    en: Latitude of a point
                keywords:
                    en: [latitude, coordinate, eastwest]
                schema:
                    type: number
                    default: null
                minOccurs: 0
                maxOccurs: 1
                metadata: null
            lng:
                title: 
                    en: Longitude
                description: 
                    en: Longitude of a point
                keywords:
                    en: [longitude, coordinate, northsouth]
                schema:
                    type: number
                    default: null
                minOccurs: 0
                maxOccurs: 1
                metadata: null
            latlng:
                title:
                    en: Latitude and Longitude
                description:
                    en: Coordinates in order [Long, Lat]
                keywords:
                    en: [coordinates, world, point]
                schema:
                    type: object
                    default: []
                minOccurs: 0
                maxOccurs: 1
                metadata: null
            sorted:
                title: 
                    en: Sorted
                description: 
                    en: 'Sort features by flow direction'
                keywords:
                    en: [downstream, upstream, unset]
                schema:
                    type: string
                    default: downstream
                minOccurs: 0
                maxOccurs: 1
                metadata: null
            sortby:
                title:
                    en: Sort By
                description:
                    en: 'Property to sort featurs with'
                keywords:
                    en: [sort, hydroseq, nameid, comid]
                schema:
                    type: string
                    default: hydroseq
                minOccurs: 0
                maxOccurs: 1
                metadata: null
        outputs:
            echo:
                title:
                    en: Feature Collection
                description:
                    en: A geoJSON Feature Collection of the River Runner process
                schema:
                    type: object
                    contentMediaType: application/json
        example:
            inputs:
                bbox: [-86.2, 39.7, -86.15, 39.75]
                sorted: downstream

